<?php

/**
 * @file
 * Uzlet Payment Fixes module file.
 *
 * Provides fixes for the moip payment method needed based on the website's
 * architecture.
 */

include_once 'uzlet_payment_fixes.features.inc';

/**
 *  Implements hook_commerce_payment_method_info_alter().
 */
function uzlet_payment_fixes_commerce_payment_method_info_alter(&$payment_methods) {
  $payment_methods['moip_ct']['active'] = TRUE;
  $payment_methods['pagseguro_payment']['active'] = FALSE;
}

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function uzlet_payment_fixes_commerce_checkout_pane_info_alter(&$checkout_panes) {

  $checkout_panes['cart_contents']['weight'] = -20;
  $checkout_panes['commerce_checkout_review_pane']['weight'] = -20;
  $checkout_panes['account']['weight'] = -19;
  $checkout_panes['customer_profile_shipping']['weight'] = -18;
  $checkout_panes['commerce_shipping']['weight'] = -17;
  $checkout_panes['stock_validation_checkout_pane']['weight'] = -16;
  $checkout_panes['extra_pane__node__50']['weight'] = -15;
  $checkout_panes['customer_profile_billing']['weight'] = -14;
  $checkout_panes['commerce_payment']['weight'] = -13;
  $checkout_panes['checkout_completion_message']['weight'] = -20;
}
