<?php

/**
 * @file
 * Uzlet Payment Fixes module file.
 *
 * Provides fixes for the moip payment method needed based on the website's
 * architecture.
 */

include_once 'uzlet_payment_fixes.features.inc';

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function uzlet_payment_fixes_commerce_checkout_pane_info_alter(&$checkout_panes) {

  $panes = array(
    'cart_contents' => -20,
    'commerce_checkout_review_pane' => -20,
    'account' => -19,
    'customer_profile_shipping' => -18,
    'commerce_shipping' => -17,
    'stock_validation_checkout_pane' => -16,
    'extra_pane__node__50' => -15,
    'customer_profile_billing' => -14,
    'commerce_payment' => -13,
    'checkout_completion_message' => -20,
  );

  foreach ($panes as $pane_id => $weight) {
    if (isset($checkout_panes[$pane_id])) {
      $checkout_panes[$pane_id]['weight'] = $weight;
    }
  }
}
