<?php

/**
 * @file
 * Contains install and update functions for Uzlet Deploy modules.
 */

/**
 * Implements hook_install().
 */
function uzlet_deploy_install() {
  uzlet_deploy_update_7100();
  uzlet_deploy_update_7101();
}

/**
 * Enable Uzlet user customization module.
 */
function uzlet_deploy_update_7100() {
  module_enable(array('uzlet_user'));
}

/**
 * Enable UzletShop Payment Fixes module.
 */
function uzlet_deploy_update_7101() {
  module_enable(array('uzletshop_payment_fixes'));
}
